# Generated by Django 5.2.6 on 2025-09-29 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
